server:
  port: 80

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/lango
    driver-class-name: org.mariadb.jdbc.Driver
    username: guest1
    password: guest1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
